"""auto_sync_1774347345

Revision ID: 00a68d2092f0
Revises: 2e118b3be7c2
Create Date: 2026-03-24 15:45:46.229005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a68d2092f0'
down_revision = '2e118b3be7c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
