"""auto_sync_1774346951

Revision ID: 2e118b3be7c2
Revises: 20260324_01
Create Date: 2026-03-24 15:39:11.796727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e118b3be7c2'
down_revision = '20260324_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_proxmox_nodes_cluster_name'), 'proxmox_nodes', ['cluster_name'], unique=False)
    op.add_column('rfid_devices', sa.Column('door_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_rfid_devices_door_id'), 'rfid_devices', ['door_id'], unique=False)
    op.create_foreign_key(None, 'rfid_devices', 'door_mappings', ['door_id'], ['id'])
    op.create_index(op.f('ix_vm_inventory_proxmox_node_id'), 'vm_inventory', ['proxmox_node_id'], unique=False)
    op.create_foreign_key(None, 'vm_inventory', 'proxmox_nodes', ['proxmox_node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vm_inventory', type_='foreignkey')
    op.drop_index(op.f('ix_vm_inventory_proxmox_node_id'), table_name='vm_inventory')
    op.drop_constraint(None, 'rfid_devices', type_='foreignkey')
    op.drop_index(op.f('ix_rfid_devices_door_id'), table_name='rfid_devices')
    op.drop_column('rfid_devices', 'door_id')
    op.drop_index(op.f('ix_proxmox_nodes_cluster_name'), table_name='proxmox_nodes')
    # ### end Alembic commands ###
