"""auto_sync_1774347595

Revision ID: 2ee65ac8664a
Revises: 00a68d2092f0
Create Date: 2026-03-24 15:49:56.237511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee65ac8664a'
down_revision = '00a68d2092f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
