"""auto_sync_1774355931

Revision ID: 52655869509d
Revises: ec4cb58fa37e
Create Date: 2026-03-24 18:08:52.023587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52655869509d'
down_revision = 'ec4cb58fa37e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
