"""Add GoldenImage and CloudInitProfile models

Revision ID: 65dc186c0faf
Revises: c83b858e25fe
Create Date: 2026-03-24 16:53:55.203397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65dc186c0faf'
down_revision = 'c83b858e25fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_init_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('ssh_keys', sa.Text(), nullable=True),
    sa.Column('network_config_json', sa.JSON(), nullable=True),
    sa.Column('custom_config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_init_profiles_name'), 'cloud_init_profiles', ['name'], unique=False)
    op.create_table('golden_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('proxmox_template_name', sa.String(length=120), nullable=False),
    sa.Column('os_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_images_name'), 'golden_images', ['name'], unique=False)
    op.create_index(op.f('ix_golden_images_proxmox_template_name'), 'golden_images', ['proxmox_template_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_golden_images_proxmox_template_name'), table_name='golden_images')
    op.drop_index(op.f('ix_golden_images_name'), table_name='golden_images')
    op.drop_table('golden_images')
    op.drop_index(op.f('ix_cloud_init_profiles_name'), table_name='cloud_init_profiles')
    op.drop_table('cloud_init_profiles')
    # ### end Alembic commands ###
