"""auto_sync_1774352818

Revision ID: 73d1e37af12e
Revises: fa54337d814b
Create Date: 2026-03-24 17:16:58.406596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d1e37af12e'
down_revision = 'fa54337d814b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
