"""auto_sync_1774352535

Revision ID: 8bafcfa66094
Revises: 65dc186c0faf
Create Date: 2026-03-24 17:12:15.639073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bafcfa66094'
down_revision = '65dc186c0faf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
