"""auto_sync_1774353488

Revision ID: 99c03305c7dc
Revises: a46bce892406
Create Date: 2026-03-24 17:28:08.784024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c03305c7dc'
down_revision = 'a46bce892406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
