"""auto_sync_1774353087

Revision ID: a46bce892406
Revises: 73d1e37af12e
Create Date: 2026-03-24 17:21:28.383372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46bce892406'
down_revision = '73d1e37af12e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
