"""auto_sync_1774347698

Revision ID: c83b858e25fe
Revises: 2ee65ac8664a
Create Date: 2026-03-24 15:51:38.911464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83b858e25fe'
down_revision = '2ee65ac8664a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
