"""auto_sync_1774355212

Revision ID: ec4cb58fa37e
Revises: 99c03305c7dc
Create Date: 2026-03-24 17:56:52.995351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4cb58fa37e'
down_revision = '99c03305c7dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
