"""auto_sync_1774352694

Revision ID: fa54337d814b
Revises: 8bafcfa66094
Create Date: 2026-03-24 17:14:54.612532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa54337d814b'
down_revision = '8bafcfa66094'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
